import fs from 'node:fs/promises';
import path from 'node:path';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
const runtime='C:/Users/aryan/.cache/codex-runtimes/codex-primary-runtime/dependencies';
process.env.RUNTIME_NODE_MODULES=`${runtime}/node/node_modules`;
const require=createRequire(`${runtime}/node/node_modules/package.json`);
const {Presentation,PresentationFile}=await import(pathToFileURL(require.resolve('@oai/artifact-tool')).href);
const skill='C:/Users/aryan/.codex/plugins/cache/openai-primary-runtime/presentations/26.909.22227/skills/presentations';
const {finalizePresentation,resolvePresentationFont}=await import(pathToFileURL(`${skill}/container_tools/artifact_tool_utils.mjs`).href);
const root=path.resolve(import.meta.dirname,'..');
const tmp=path.join(root,'tmp/deck');await fs.mkdir(tmp,{recursive:true});await fs.mkdir(path.join(root,'presentation'),{recursive:true});
const font=resolvePresentationFont();
const p=Presentation.create({slideSize:{width:1280,height:720}});
const slides=[
['GridWatch','Power outage prediction & grid equipment failure advisor\n\nU1 / IBM Bobathon 2026\nWorking local prototype', 'Team GridWatch · Lead: Vivaa Rathod. Based on the supplied U1 problem statement.'],
['The operator decision','Which asset needs attention before the next outage?\n\nSensor condition and weather inform likelihood.\nCustomer exposure and critical sites inform priority.\nCrew skills and shift capacity constrain the response.','Source: Industry Problem Statements - 2026.pdf, U1. No cost savings are claimed.'],
['Prediction and planning','Real ETT observations train a 24-hour oil-temperature forecast.\n\nA separate simulator trains the failure classifier.\nThe advisor combines risk with fictional grid impact.\nThe planner proposes jobs and crew staging locations.','ETT source: https://github.com/zhouhaoyi/ETDataset. The temperature model is separate from the synthetic outage model.'],
['Measured holdout results','Real temperature forecast\n1.63°C MAE versus 1.71°C persistence baseline\n\nSynthetic failure classifier\n0.772 average precision versus 0.512 threshold baseline\n\nBoth benchmarks use later-time test periods.','Source: models/metrics.json generated by src/train.py. ETT test n=3446, synthetic test n=2556. Synthetic event prevalence 43.23%. Results do not establish real-world outage accuracy.'],
['IBM Bob integration','Bob calls the local GridWatch MCP server.\n\nassess_grid_risk returns probabilities, evidence and crew plans.\nget_model_evaluation returns the measured benchmarks.\n\nBob can produce a brief grounded in these tool results.','Official configuration: https://bob.ibm.com/docs/ide/configuration/mcp/mcp-in-bob. Signed-in IBM Bob UI verification is a separate pending step.'],
['Field validation and impact','The prototype makes priorities and resource gaps inspectable.\n\nNext: obtain timestamped utility failures and archived forecasts.\nValidate on later periods and unseen equipment.\nMeasure false alerts, lead time and recall at a crew budget.\n\nNo live dispatch, validated outage accuracy or savings are claimed.','Source: docs/model-card.md. This is a proposed validation plan, not completed field work.']
];
for(let i=0;i<slides.length;i++){
 const [title,body,notes]=slides[i];const s=p.slides.add();s.background.fill=i===0?'#102C3D':'#F6F9FA';
 const add=(text,left,top,width,height,size,color,bold=false)=>{const shape=s.shapes.add({geometry:'textbox',position:{left,top,width,height},fill:'none',line:{fill:'none',width:0}});shape.text=text;shape.text.style={typeface:font,fontSize:size,color,bold,autoFit:'none'};};
 add(title,80,70,1120,95,i===0?64:45,i===0?'#FFFFFF':'#102C3D',true);
 add(body,80,210,1100,390,29,i===0?'#BFDFDD':'#294757');
 add(String(i+1).padStart(2,'0'),80,650,100,30,16,i===0?'#70E0CC':'#58707E');
 s.speakerNotes.textFrame.setText(notes);
 const preview=await p.export({slide:s,format:'png',scale:1});await fs.writeFile(path.join(tmp,`slide-${i+1}.png`),new Uint8Array(await preview.arrayBuffer()));
}
const candidate=path.join(tmp,'candidate.pptx');await(await PresentationFile.exportPptx(p)).save(candidate);
const result=await finalizePresentation({workspaceDir:root,candidatePath:candidate,finalPath:path.join(root,'presentation/slides.pptx'),pythonExecutable:`${runtime}/python/python.exe`,integrityValidatorPath:`${skill}/container_tools/inspect_presentation_package_integrity.py`,layoutValidatorPath:`${skill}/container_tools/inspect_presentation_layout_geometry.py`,layoutArgs:['--expected-slide-size-emu','12192000,6858000','--validate-heading-fit'],fontPolicy:{basis:'design',families:[font]},verifyArtifactToolImport:true,receiptPath:path.join(tmp,'validation.json')});
console.log(JSON.stringify(result));
